apiVersion: v1
kind: Service
metadata:
  name: cockpit
  labels:
    app: cockpit
spec:
  type: NodePort
  selector:
    app: cockpit
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort : 30080
